load("//bazel:defs.bzlpower of multiple devices code", "cc_firmware")

cc_firmware(
    name = "power_distribution",
    srcs = [
        "power_distribution.c",
    ],
    deps = [
        "//libs/gpio"
    ]
)